/* VLYOR HYDRA — hydra.i18n.js · Traducción editorial EN / ES */
'use strict';
const HYDRA_TRANSLATIONS = {
  'hy.tag'  : { en: 'Humectants & Film Agents — 7 Actives Across 3 Families',
                es: 'Humectantes y Agentes Formadores de Film — 7 Activos en 3 Familias' },
  'hy.sub'  : { en: 'Seven humectants and film-formers — from pharmacopoeial-grade PEG and glycols through high-molecular-weight PVP styling polymers. The hydration and film-formation architecture that determines how a formula feels on skin and performs on hair.',
                es: 'Siete humectantes y formadores de film — desde PEG y glicoles de calidad farmacopeica hasta polímeros de estilizado PVP de alto peso molecular. La arquitectura de hidratación y formación de film que determina cómo se siente una fórmula en la piel y cómo rinde en el cabello.' },

  'hy.stat.1': { en: 'Humectant & Film-Former Actives', es: 'Activos Humectantes y Formadores de Film' },
  'hy.stat.2': { en: 'Full MW Spectrum',                es: 'Espectro Completo de PM'                 },
  'hy.stat.3': { en: 'Pharmacopoeial Quality',          es: 'Calidad Farmacopeica'                    },
  'hy.stat.4': { en: 'All Actives Listed',              es: 'Todos los Activos Listados'               },

  'hy.in1.h' : { en: 'Full Molecular Weight Spectrum',  es: 'Espectro Completo de Peso Molecular'      },
  'hy.in1.b' : { en: 'AquaForm PEG Series covers PEG 200 to PEG 8000 — from mobile clear liquids for humectancy and solubilisation through waxy solid grades for ointment bases, consistency modification and sustained moisture release. Eight grades, one family, every application covered.',
                 es: 'La Serie AquaForm PEG cubre desde PEG 200 hasta PEG 8000 — desde líquidos claros y fluidos para humectancia y solubilización hasta grados sólidos cerosos para bases de ungüentos, modificación de consistencia y liberación de humedad sostenida. Ocho grados, una familia, cada aplicación cubierta.' },
  'hy.in2.h' : { en: 'Glycol Architecture',             es: 'Arquitectura de Glicoles'                 },
  'hy.in2.b' : { en: 'HydraBase Glyc (Glycerin), PG (Propylene Glycol), DPG (Dipropylene Glycol) and PDO (1,3-Propanediol) form the complete classical humectant toolkit — moisture binding, solvent function and skin feel engineering from three complementary molecular architectures.',
                 es: 'HydraBase Glicol (Glicerina), PG (Propilenglicol), DPG (Dipropilenglicol) y PDO (1,3-Propanodiol) forman el conjunto completo de herramientas humectantes clásicas — retención de humedad, función solvente e ingeniería de la sensación cutánea desde tres arquitecturas moleculares complementarias.' },
  'hy.in3.h' : { en: 'Film-Former Architecture',        es: 'Arquitectura de Formador de Film'         },
  'hy.in3.b' : { en: 'AquaFilm K30 and K90 — Polyvinylpyrrolidone in medium (K30) and high (K90) molecular weight grades. The reference nonionic film former for hair styling: stiff, transparent, glossy films from K30; high-hold, high-viscosity performance from K90.',
                 es: 'AquaFilm K30 y K90 — Polivinilpirrolidona en grados de peso molecular medio (K30) y alto (K90). El formador de film no iónico de referencia para el estilizado capilar: films rígidos, transparentes y brillantes con K30; alto fijado y alto rendimiento de viscosidad con K90.' },
  'hy.in4.h' : { en: 'Pharmacopoeial Standard',         es: 'Estándar Farmacopeico'                   },
  'hy.in4.b' : { en: 'Every HYDRA active is supplied to USP/NF or equivalent pharmacopoeial quality — glycerin BP/USP, propylene glycol USP, PEG grades meeting pharmacopoeial specifications. The documentation standard demanded by regulated markets globally.',
                 es: 'Cada activo HYDRA se suministra con calidad USP/NF o farmacopeica equivalente — glicerina BP/USP, propilenglicol USP, grados PEG que cumplen las especificaciones farmacopeicas. El estándar de documentación exigido por los mercados regulados a nivel global.' },

  'hy.comm.eyebrow': { en: 'The Hydration Argument',     es: 'El Argumento de la Hidratación'          },
  'hy.comm.title'  : { en: 'Moisture retention is\nnot a claim. It is\na formulation decision.',
                       es: 'La retención de humedad\nno es un claim. Es\nuna decisión de formulación.' },
  'hy.comm.p1'     : { en: 'Every cosmetic formula exists in a constant battle with water loss. Emulsions lose water to evaporation. Gels lose water to the environment. Hair loses water under thermal stress. The ingredients that determine whether a formula wins or loses this battle are humectants and film formers — the invisible hydration infrastructure of personal care.',
                       es: 'Toda fórmula cosmética existe en una batalla constante contra la pérdida de agua. Las emulsiones pierden agua por evaporación. Los geles pierden agua hacia el entorno. El cabello pierde agua bajo el estrés térmico. Los ingredientes que determinan si una fórmula gana o pierde esta batalla son los humectantes y los formadores de film — la infraestructura de hidratación invisible del cuidado personal.' },
  'hy.comm.p2'     : { en: '<strong>VLYOR HYDRA</strong> provides the complete humectant and film-former toolkit: the AquaForm PEG series spanning every molecular weight from mobile liquid to waxy solid; the HydraBase glycol family covering the four most commercially important humectant glycols; and the AquaFilm PVP series for transparent, shiny, adjustable-hold film-forming performance across the full styling spectrum.',
                       es: '<strong>VLYOR HYDRA</strong> proporciona el conjunto completo de herramientas humectantes y formadoras de film: la serie AquaForm PEG que abarca todos los pesos moleculares desde líquido fluido hasta sólido ceroso; la familia de glicoles HydraBase que cubre los cuatro glicoles humectantes comercialmente más importantes; y la serie AquaFilm PVP para un rendimiento formador de film transparente, brillante y de fijación ajustable en todo el espectro de estilizado.' },
  'hy.comm.p3'     : { en: 'In global climate diversity — where humidity varies from the tropical moisture of Southeast Asia and Brazil to the arid conditions of the Middle East and North Africa — humectant selection is not neutral. The wrong humectant at the wrong concentration produces sticky, heavy skin feel in humid conditions, or insufficient moisturisation in dry conditions. <strong>VLYOR HYDRA provides the molecular toolkit to engineer moisture behaviour precisely for any target climate and market.</strong>',
                       es: 'En la diversidad climática global — donde la humedad varía desde la humedad tropical del Sudeste Asiático y Brasil hasta las condiciones áridas de Oriente Medio y el norte de África — la selección del humectante no es neutral. El humectante equivocado a la concentración equivocada produce una sensación cutánea pegajosa y pesada en condiciones húmedas, o una hidratación insuficiente en condiciones secas. <strong>VLYOR HYDRA proporciona el conjunto de herramientas moleculares para diseñar el comportamiento de la humedad con precisión para cualquier clima y mercado objetivo.</strong>' },

  'hy.port.eyebrow': { en: 'The HYDRA Portfolio',      es: 'El Portafolio HYDRA'                      },
  'hy.port.title'  : { en: '7 actives.\nOne hydration system.',
                       es: '7 activos.\nUn sistema de hidratación.'                                    },
  'hy.port.sub'    : { en: 'Select any active to access its full commercial profile, technical specifications, water-binding data and formulation guidance.',
                       es: 'Seleccione cualquier activo para acceder a su perfil comercial completo, especificaciones técnicas, datos de unión de agua y orientación de formulación.' },

  'hy.sec.apps' : { en: 'Applications',              es: 'Aplicaciones'                 },
  'hy.sec.syn'  : { en: 'Synergistic Combinations',  es: 'Combinaciones Sinérgicas'     },
  'hy.sec.notes': { en: 'Formulation Notes',          es: 'Notas de Formulación'        },
  'hy.sec.comp' : { en: 'Global Compliance',          es: 'Cumplimiento Global'          },

  /* ── AQUAFORM PEG ─────────────────────────────────────────────────────────── */
  'hy.peg.tagline': { en: '"Eight grades of Polyethylene Glycol spanning molecular weight 200 to 8000 — from mobile clear liquids for humectancy and solubilisation through waxy solid flakes for consistency modification and ointment bases."',
                      es: '"Ocho grados de Polietilenglicol con peso molecular de 200 a 8000 — desde líquidos claros y fluidos para humectancia y solubilización hasta escamas sólidas cerosas para modificación de consistencia y bases de ungüentos."' },
  'hy.peg.p1'     : { en: 'AquaForm PEG Series is <strong>Polyethylene Glycol (PEG) — a family of linear polyether polymers</strong>. <strong>PEG 200, 400, 600</strong> are clear liquids with increasing viscosity; <strong>PEG 1000–1500</strong> are pastes or soft solids; <strong>PEG 4000, 6000 and 8000</strong> are white waxy flakes. This molecular weight spectrum produces fundamentally different formulation functions from a single INCI chemistry.',
                      es: 'La Serie AquaForm PEG es <strong>Polietilenglicol (PEG) — una familia de polímeros poliéter lineales</strong>. <strong>PEG 200, 400, 600</strong> son líquidos claros de viscosidad creciente; <strong>PEG 1000–1500</strong> son pastas o sólidos blandos; <strong>PEG 4000, 6000 y 8000</strong> son escamas cerosas blancas. Este espectro de pesos moleculares produce funciones de formulación fundamentalmente diferentes desde una sola química INCI.' },
  'hy.peg.p2'     : { en: 'Liquid grades (PEG 200–600) act as <strong>humectants, solvents and solubilisers</strong>. <strong>PEG 400</strong> is the most commercially used grade globally. Solid grades (PEG 4000–8000) function as <strong>consistency factors, ointment bases and water-soluble alternatives to traditional waxes</strong>. All grades meet USP/NF pharmacopoeial standards.',
                      es: 'Los grados líquidos (PEG 200–600) actúan como <strong>humectantes, solventes y solubilizantes</strong>. <strong>PEG 400</strong> es el grado más utilizado comercialmente a nivel global. Los grados sólidos (PEG 4000–8000) funcionan como <strong>factores de consistencia, bases de ungüentos y alternativas solubles en agua a las ceras tradicionales</strong>. Todos los grados cumplen los estándares farmacopeicos USP/NF.' },
  'hy.peg.apps'   : { en: ['Humectant in Creams & Lotions (PEG 200–600)','Active Solubilisation (PEG 400)','Ointment Bases & Consistency (PEG 4000–8000)','Cold Cream / Water-Washable Bases','Tablet Binder (PEG 6000)','Fragrance Carrier'],
                      es: ['Humectante en Cremas y Lociones (PEG 200–600)','Solubilización de Activos (PEG 400)','Bases de Ungüentos y Consistencia (PEG 4000–8000)','Cremas Frías / Bases Lavables con Agua','Aglutinante para Comprimidos (PEG 6000)','Vehículo de Fragancias'] },

  /* ── HYDRABASE GLYC ───────────────────────────────────────────────────────── */
  'hy.glyc.tagline': { en: '"Glycerin — the most widely used humectant in cosmetics globally. USP / BP / EP pharmacopoeial quality from vegetable origin, providing the highest water-binding capacity of all glycols at 25% of its weight at 50% relative humidity."',
                       es: '"Glicerina — el humectante más ampliamente utilizado en cosmética a nivel global. Calidad farmacopeica USP / BP / EP de origen vegetal, proporcionando la mayor capacidad de unión de agua de todos los glicoles al 25% de su peso a 50% de humedad relativa."' },
  'hy.glyc.p1'     : { en: 'HydraBase Glyc is <strong>Glycerin (Glycerol) — the triol humectant</strong> with three hydroxyl groups per molecule. Glycerin is the most commercially important humectant in personal care. At 50% relative humidity, glycerin absorbs approximately 25% of its own weight in water from the environment — drawing moisture continuously from the ambient air into the formulation and skin surface.',
                       es: 'HydraBase Glyc es <strong>Glicerina (Glicerol) — el humectante triol</strong> con tres grupos hidroxilo por molécula. La glicerina es el humectante comercialmente más importante en el cuidado personal. A 50% de humedad relativa, la glicerina absorbe aproximadamente el 25% de su propio peso en agua del entorno — atrayendo humedad continuamente del aire ambiente hacia la formulación y la superficie cutánea.' },
  'hy.glyc.apps'   : { en: ['Moisturisers & Creams (1–8%)','Shampoos & Conditioners (1–3%)','Body Washes & Cleansers','Natural / COSMOS Formulations','Serums & Toners','Sunscreen Hydration'],
                       es: ['Hidratantes y Cremas (1–8%)','Champús y Acondicionadores (1–3%)','Geles de Baño y Limpiadores','Formulaciones Naturales / COSMOS','Serums y Tónicos','Hidratación en Protectores Solares'] },

  /* ── HYDRABASE PG ─────────────────────────────────────────────────────────── */
  'hy.pg.tagline': { en: '"Propylene Glycol — the workhorse multifunctional humectant. USP quality, low viscosity, outstanding solubilisation of fragrances and actives, non-sticky feel and exceptional compatibility across the full cosmetic formulation range."',
                     es: '"Propilenglicol — el humectante multifuncional de uso general. Calidad USP, baja viscosidad, solubilización sobresaliente de fragancias y activos, sensación no pegajosa y compatibilidad excepcional en toda la gama de formulación cosmética."' },
  'hy.pg.p1'     : { en: 'HydraBase PG is <strong>Propylene Glycol (1,2-Propanediol) — the diol humectant</strong> with two hydroxyl groups per molecule. It provides water-binding at 50% RH of approximately 20% of its weight — slightly below glycerin but without glycerin\'s stickiness at comparable concentrations. Its low molecular weight (76 g/mol), low viscosity and outstanding compatibility make it the most versatile multifunctional humectant available.',
                     es: 'HydraBase PG es <strong>Propilenglicol (1,2-Propanodiol) — el humectante diol</strong> con dos grupos hidroxilo por molécula. Proporciona unión de agua a 50% HR de aproximadamente el 20% de su peso — ligeramente por debajo de la glicerina pero sin la pegajosidad de ésta a concentraciones comparables. Su bajo peso molecular (76 g/mol), baja viscosidad y compatibilidad sobresaliente lo convierten en el humectante multifuncional más versátil disponible.' },
  'hy.pg.apps'   : { en: ['All Cosmetic Formulations (humectant)','Fragrance Solubilisation','Active Delivery Vehicle','Preservation Boost','Shampoo & Conditioner','Sunscreen Vehicles'],
                     es: ['Todas las Formulaciones Cosméticas (humectante)','Solubilización de Fragancias','Vehículo de Entrega de Activos','Potenciación de Conservación','Champú y Acondicionador','Vehículos para Protectores Solares'] },

  /* ── HYDRABASE DPG ────────────────────────────────────────────────────────── */
  'hy.dpg.tagline': { en: '"Dipropylene Glycol — the premium humectant and fragrance carrier. Higher molecular weight than Propylene Glycol produces a lighter, drier skin feel with superior fragrance-carrying capacity."',
                      es: '"Dipropilenglicol — el humectante premium y vehículo de fragancias. El mayor peso molecular que el Propilenglicol produce una sensación cutánea más ligera y seca con superior capacidad de transporte de fragancias."' },
  'hy.dpg.p1'     : { en: 'HydraBase DPG is <strong>Dipropylene Glycol (DPG)</strong>. Its higher molecular weight versus PG (134 g/mol vs. 76 g/mol) produces a liquid with a markedly lighter, less tacky skin feel than propylene glycol at equivalent concentrations. This improved aesthetic profile makes DPG the preferred humectant for premium skin care formulations.',
                      es: 'HydraBase DPG es <strong>Dipropilenglicol (DPG)</strong>. Su mayor peso molecular frente al PG (134 g/mol vs. 76 g/mol) produce un líquido con una sensación cutánea marcadamente más ligera y menos pegajosa que el propilenglicol a concentraciones equivalentes. Este perfil estético mejorado convierte al DPG en el humectante preferido para las formulaciones de cuidado de la piel premium.' },
  'hy.dpg.p2'     : { en: 'DPG is also the <strong>standard carrier solvent for fragrance concentrates</strong> in personal care: its low odour, excellent solubilisation of essential oils and compatibility with both water-soluble and oil-soluble perfume components make it the industry-standard fragrance carrier in fine fragrance, body mist and eau de toilette formulations.',
                      es: 'El DPG es también el <strong>solvente vehículo estándar para los concentrados de fragancias</strong> en el cuidado personal: su bajo olor, la excelente solubilización de aceites esenciales y la compatibilidad con los componentes de perfume tanto hidrosolubles como liposolubles lo convierten en el vehículo de fragancias estándar de la industria en las formulaciones de perfumería fina, brumas corporales y eau de toilette.' },
  'hy.dpg.apps'   : { en: ['Premium Skin Care Humectant','Fragrance Carrier / Perfume Diluent','Body Mist & Eau de Toilette','Deodorant & Antiperspirant Base','Toners & Essences','Aftershave Formulations'],
                      es: ['Humectante para Cuidado de la Piel Premium','Vehículo de Fragancias / Diluyente de Perfume','Bruma Corporal y Eau de Toilette','Base de Desodorante y Antitranspirante','Tónicos y Esencias','Formulaciones Aftershave'] },

  /* ── HYDRABASE PDO ────────────────────────────────────────────────────────── */
  'hy.pdo.apps'   : { en: ['Natural / COSMOS Formulations','Clean-Label Skin Care','Premium Moisturisers','Natural Hair Care','Active Solubilisation','PG-Free Formulations'],
                      es: ['Formulaciones Naturales / COSMOS','Cuidado de la Piel de Etiqueta Limpia','Hidratantes Premium','Cuidado Capilar Natural','Solubilización de Activos','Formulaciones Sin PG'] },

  /* ── AQUAFILM K30 ─────────────────────────────────────────────────────────── */
  'hy.k30.tagline': { en: '"PVP K30 — the medium molecular weight polyvinylpyrrolidone for spray and liquid styling applications. Produces stiff, transparent, shiny films from clear solution at 3–6% loading."',
                      es: '"PVP K30 — la polivinilpirrolidona de peso molecular medio para aplicaciones de spray y estilizado líquido. Produce films rígidos, transparentes y brillantes desde solución clara a una carga del 3–6%."' },
  'hy.k30.p1'     : { en: 'AquaFilm K30 is <strong>Polyvinylpyrrolidone at K-value 30 — a nonionic, water-soluble homopolymer of N-vinylpyrrolidone</strong> with molecular weight approximately 40,000–58,000 g/mol. PVP is the reference nonionic hair styling polymer globally. It forms <strong>stiff, transparent, highly glossy films</strong> on hair fibres when the water carrier evaporates after product application.',
                      es: 'AquaFilm K30 es <strong>Polivinilpirrolidona a K-valor 30 — un homopolímero de N-vinilpirrolidona no iónico y soluble en agua</strong> con peso molecular de aproximadamente 40.000–58.000 g/mol. El PVP es el polímero de estilizado capilar no iónico de referencia a nivel global. Forma <strong>films rígidos, transparentes y muy brillantes</strong> en las fibras capilares cuando el vehículo acuoso se evapora tras la aplicación del producto.' },
  'hy.k30.p2'     : { en: 'The medium molecular weight of K30 produces the <strong>ideal viscosity-performance balance for spray applications</strong>: at 3–6% in water or water-alcohol vehicle, K30 solutions remain sufficiently low viscosity for pump sprays and aerosol valves while delivering adequate film-forming molecular weight for hair hold performance.',
                      es: 'El peso molecular medio del K30 produce el <strong>equilibrio ideal viscosidad-rendimiento para aplicaciones en spray</strong>: al 3–6% en vehículo de agua o agua-alcohol, las soluciones de K30 mantienen una viscosidad suficientemente baja para sprays de bomba y válvulas de aerosol mientras entrega el peso molecular formador de film adecuado para el rendimiento de fijación capilar.' },
  'hy.k30.apps'   : { en: ['Pump Spray Hair Stylers','Hair Setting Lotions','Styling Mousses & Gels','Wet-Look Gel Systems','Hair Spray (alcohol-based)','Pigment Dispersant in Colour Cosmetics'],
                      es: ['Estilizadores Capilares en Spray de Bomba','Lociones Fijadoras','Mousses y Geles de Estilizado','Sistemas de Gel Wet-Look','Laca Capilar (a base de alcohol)','Dispersante de Pigmentos en Cosméticos de Color'] },

  /* ── AQUAFILM K90 ─────────────────────────────────────────────────────────── */
  'hy.k90.tagline': { en: '"PVP K90 — the high molecular weight polyvinylpyrrolidone for maximum hold and viscosity-critical styling applications. Higher MW produces stronger, more durable hair films with greater hold force than K30 at equivalent concentration."',
                      es: '"PVP K90 — la polivinilpirrolidona de alto peso molecular para el máximo fijado y aplicaciones de estilizado críticas en viscosidad. El mayor PM produce films capilares más fuertes y duraderos con mayor fuerza de fijación que el K30 a concentración equivalente."' },
  'hy.k90.p1'     : { en: 'AquaFilm K90 is <strong>Polyvinylpyrrolidone at K-value 90 — the high molecular weight grade</strong> with molecular weight approximately 900,000–1,500,000 g/mol. The dramatically higher molecular weight versus K30 produces: <strong>significantly stronger, more durable films</strong> with higher hold force per unit mass of polymer, better adhesion to hair fibres and superior resistance to humidity-induced film softening.',
                      es: 'AquaFilm K90 es <strong>Polivinilpirrolidona a K-valor 90 — el grado de alto peso molecular</strong> con peso molecular de aproximadamente 900.000–1.500.000 g/mol. El peso molecular dramáticamente mayor que el K30 produce: <strong>films significativamente más fuertes y duraderos</strong> con mayor fuerza de fijación por unidad de masa de polímero, mejor adhesión a las fibras capilares y mayor resistencia al ablandamiento del film inducido por la humedad.' },
  'hy.k90.p2'     : { en: 'K90 is used at <strong>lower concentrations (1–3%)</strong> where it provides equivalent or superior hold to K30 at 3–6%, or blended with K30 to achieve an intermediate MW profile. Pure K90 applications are primarily <strong>gel-format styling products</strong> where high viscosity is a desired product attribute.',
                      es: 'El K90 se usa a <strong>concentraciones más bajas (1–3%)</strong> donde proporciona un fijado equivalente o superior al K30 al 3–6%, o se mezcla con K30 para lograr un perfil de PM intermedio. Las aplicaciones de K90 puro son principalmente <strong>productos de estilizado en formato gel</strong> donde la alta viscosidad es un atributo deseado del producto.' },
  'hy.k90.apps'   : { en: ['Hair Gel & Wet-Look Gel','Strong-Hold Styling Creams','Hair Pomades & Waxes','Maximum Hold Mousses','Blended K30/K90 Spray Systems','Film-Forming Base for Colour Cosmetics'],
                      es: ['Gel Capilar y Gel Wet-Look','Cremas de Estilizado de Fijación Fuerte','Pomadas y Ceras Capilares','Mousses de Máximo Fijado','Sistemas de Spray K30/K90 Mezclados','Base Formadora de Film para Cosméticos de Color'] },

  /* ── COMPLIANCE SECTION ───────────────────────────────────────────────────── */
  'hy.comp.eyebrow': { en: 'Global Compliance',      es: 'Cumplimiento Global'               },
  'hy.comp.title'  : { en: 'Every market.\nEvery standard.',
                       es: 'Cada mercado.\nCada estándar.'                                    },
  'hy.comp.sub'    : { en: 'All 7 HYDRA actives comply with EU, LATAM and global cosmetic regulatory frameworks. Glycerin, Propylene Glycol and PEG grades meet USP / BP / EP pharmacopoeial standards — the documentation expected by regulated global markets.',
                       es: 'Los 7 activos HYDRA cumplen con los marcos regulatorios cosméticos de la UE, LATAM y globales. La glicerina, el propilenglicol y los grados PEG cumplen los estándares farmacopeicos USP / BP / EP — la documentación esperada por los mercados regulados a nivel global.' },

  /* ── CTA ──────────────────────────────────────────────────────────────────── */
  'hy.cta.title': { en: 'Ready to engineer\nthe moisture architecture\nyour formula needs?',
                    es: '¿Listo para diseñar\nla arquitectura de humedad\nque su fórmula necesita?' },
  'hy.cta.p'    : { en: 'Our humectant formulation team provides concentration optimisation, climate-specific moisture design, regulatory documentation and full technical dossiers for every HYDRA active.',
                    es: 'Nuestro equipo de formulación de humectantes ofrece optimización de concentración, diseño de humedad específico para cada clima, documentación regulatoria y dossiers técnicos completos para cada activo HYDRA.' },

  /* ── BIZ VALUE ────────────────────────────────────────────────────────────── */
  'hy.biz.n1': { en: '25% vs 18%',    es: '25% vs 18%'    },
  'hy.biz.t1': { en: 'Not all humectants bind the same amount of water',
                 es: 'No todos los humectantes retienen la misma cantidad de agua' },
  'hy.biz.p1': { en: 'HydraBase Glyc binds 25% of its weight in water at 50% relative humidity. HydraBase PDO binds 18%. At a 5% formulation loading, the difference is 0.35 g of water per 100 g of formula — imperceptible on paper, perceptible on skin over 8 hours. In climates with low ambient humidity, that 0.35 g is the difference between a moisturiser that works and one that leaves skin feeling tight by midday.',
                 es: 'HydraBase Glyc retiene el 25% de su peso en agua a 50% de humedad relativa. HydraBase PDO retiene el 18%. A una carga de formulación del 5%, la diferencia es de 0,35 g de agua por 100 g de fórmula — imperceptible en papel, perceptible en la piel tras 8 horas. En climas con baja humedad ambiental, ese 0,35 g es la diferencia entre un hidratante que funciona y uno que deja la piel tensa al mediodía.' },
  'hy.biz.n2': { en: 'Bio-based',     es: 'De origen bio'  },
  'hy.biz.t2': { en: 'HydraBase PDO — the bio-based humectant with a different declaration',
                 es: 'HydraBase PDO — el humectante de origen biológico con una declaración diferente' },
  'hy.biz.p2': { en: 'HydraBase PDO (1,3-Propanediol) from corn fermentation is COSMOS-eligible and can be declared as "bio-based" on product communication. Propylene Glycol cannot. At equivalent formulation cost, PDO opens natural retail channels, COSMOS certification pathways and clean-label positioning that PG closes. The ingredient decision is also a distribution decision.',
                 es: 'HydraBase PDO (1,3-Propanodiol) de fermentación de maíz es elegible para COSMOS y puede declararse como "de origen biológico" en la comunicación del producto. El Propilenglicol no puede. A un coste de formulación equivalente, el PDO abre canales de venta minorista natural, vías de certificación COSMOS y posicionamiento de etiqueta limpia que el PG cierra. La decisión del ingrediente es también una decisión de distribución.' },
  'hy.biz.n3': { en: 'K30 vs K90',   es: 'K30 vs K90'     },
  'hy.biz.t3': { en: 'PVP grade selection determines the hold level you can claim',
                 es: 'La selección del grado de PVP determina el nivel de fijación que puede declarar' },
  'hy.biz.p3': { en: 'AquaFilm K90 at 1% delivers 2–3× the styling hold force of AquaFilm K30 at 3–5%. The K90 formula uses less polymer, has lower ingredient cost per unit, and delivers a stronger consumer-perceptible result. The grade choice is not technical preference — it is the product architecture decision that determines what you can claim on the packaging.',
                 es: 'AquaFilm K90 al 1% entrega 2–3 veces la fuerza de fijación de AquaFilm K30 al 3–5%. La fórmula con K90 utiliza menos polímero, tiene menor coste de ingrediente por unidad y entrega un resultado más fuerte perceptible por el consumidor. La elección del grado no es preferencia técnica — es la decisión de arquitectura del producto que determina lo que puede declarar en el envase.' },
};
if (typeof VLYOR_TRANSLATIONS !== 'undefined') { Object.assign(VLYOR_TRANSLATIONS, HYDRA_TRANSLATIONS); }
